const api = globalThis.browser ?? globalThis.chrome;
const defaults = { provider: "openai-compatible", protocol: "https", host: "api.openai.com", port: "443", path: "/v1/chat/completions", modelsPath: "/v1/models", model: "gpt-4o-mini", authType: "bearer", apiKey: "", sendImages: true, vision: "auto", maxImageSizeKb: "1024" };
const ids = Object.keys(defaults); const $ = (id) => document.querySelector(`#${id}`);
const form = $("settings-form"); const auth = $("authType"); const status = $("status"); const modelSelect = $("modelSelect"); const modelsList = $("models-list"); let current = { ...defaults };
function updateAuth() { $("key-field").hidden = auth.value === "none"; }
function updateModelMeta(model) { const found = (current.models || []).find((item) => item.id === model); $("selected-model-meta").textContent = found ? `${found.vision ? "Vision вероятно поддерживается" : "Только текст по metadata/эвристике"} · ${found.owned_by || "провайдер не указан"}` : "Модель не выбрана или введена вручную."; }
function collect() { return { ...current, ...Object.fromEntries(ids.map((id) => [id, $(id).type === "checkbox" ? $(id).checked : $(id).value.trim()])) }; }
async function save(show = true) { current = collect(); await api.storage.local.set({ autoSolve: current }); if (show) { status.className = "status"; status.textContent = "Настройки сохранены."; setTimeout(() => { status.textContent = ""; }, 2500); } }
function renderModels(models) { current.models = models; modelSelect.replaceChildren(new Option(models.length ? "Выберите модель…" : "Модели не найдены", "")); models.forEach((item) => modelSelect.append(new Option(`${item.id}${item.vision ? " · vision" : ""}`, item.id))); modelSelect.value = current.model || ""; modelsList.replaceChildren(); if (models.length) { const table = document.createElement("table"); table.className = "model-table"; table.innerHTML = "<thead><tr><th>Модель</th><th>Vision</th><th>Владелец</th></tr></thead>"; const body = document.createElement("tbody"); models.forEach((item) => { const row = document.createElement("tr"); const name = document.createElement("td"); name.textContent = item.id; const vision = document.createElement("td"); vision.textContent = item.vision ? "вероятно да" : "не определено"; vision.className = item.vision ? "vision" : "vision text-vision"; const owner = document.createElement("td"); owner.textContent = item.owned_by || "—"; row.append(name, vision, owner); body.append(row); }); table.append(body); modelsList.append(table); } updateModelMeta(current.model); }
async function loadModels(test = false) { await save(false); status.className = "status"; status.textContent = test ? "Проверяю подключение…" : "Загружаю список моделей…"; const result = await api.runtime.sendMessage({ type: test ? "TEST_PROVIDER" : "LIST_MODELS" }); if (!result?.ok) { status.className = "status error"; status.textContent = result?.error || "Не удалось получить список моделей."; return; } current.latencyMs = result.latencyMs; renderModels(result.models || []); status.className = "status"; status.textContent = `Подключение успешно · ${result.models?.length || 0} моделей${result.latencyMs ? ` · ${result.latencyMs} мс` : ""}`; await api.storage.local.set({ autoSolve: current }); }
async function load() { const result = await api.storage.local.get("autoSolve"); current = { ...defaults, ...(result.autoSolve || {}) }; ids.forEach((id) => { if ($(id).type === "checkbox") $(id).checked = current[id] !== false; else $(id).value = current[id] ?? defaults[id]; }); updateAuth(); if (Array.isArray(current.models)) renderModels(current.models); else updateModelMeta(current.model); }
auth.addEventListener("change", updateAuth); modelSelect.addEventListener("change", () => { $("model").value = modelSelect.value; current.model = modelSelect.value; updateModelMeta(current.model); }); $("refresh-models").addEventListener("click", () => loadModels(false)); $("test").addEventListener("click", () => loadModels(true)); form.addEventListener("submit", (event) => { event.preventDefault(); save(true); }); load().catch((error) => { status.className = "status error"; status.textContent = error.message; });
